# Generated by Django 3.2 on 2024-11-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'Пользователь'), ('Moderator', 'Модератор'), ('Admin', 'Администратор'), ('Superuser', 'Суперпользователь')], max_length=16, verbose_name='Роль'),
        ),
    ]
