# Generated by Django 3.2 on 2024-11-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241112_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'Пользователь'), ('Moderator', 'Модератор'), ('Admin', 'Администратор'), ('Superuser', 'Суперпользователь')], default=('User', 'Пользователь'), max_length=16, verbose_name='Роль'),
        ),
    ]
