# Generated by Django 3.2 on 2024-11-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241114_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titlegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titlegenre',
            name='title',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
