# Generated by Django 3.2 on 2024-11-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'коментарии',
                'ordering': ('pub_date', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('pub_date', 'id'), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
