# Generated by Django 3.2 on 2024-11-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20241115_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='raview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='titles.reviews'),
            preserve_default=False,
        ),
    ]
