# Generated by Django 3.2 on 2024-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_comments_raview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='raview',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.IntegerField(null=True),
        ),
    ]
